### ISSUE TITLE
验证集正确率的问题

### ISSUE THREAD

**Issue by YaooXu** [pprp/captcha_identify.pytorch#2]
验证集上正确率一直是0可能是什么情况导致的，batch_size=128, RES101.

**Comment by pprp** [comment]
使用的模型应该与解决的问题一致，res101模型容量可能比较大，这个需要比较仔细的调参才能让其开始收敛，过几天我会重新放出一个库，你可以关注一下，里边有我调参的过程，也有一些trick,效果比较好。

**Comment by pprp** [comment]
https://github.com/pprp/captcha.Pytorch
这是我最新开源的模型更加丰富的库，比当前的库更容易调参，欢迎试试

**Comment by YaooXu** [comment]
您好，感谢回复，正好我也参加了那个比赛，个人觉得res18针对此问题都有点复杂了，如果不增强数据很容易过拟合，建议最后加上CTC loss，对效果提升很大，给您star，相互学习~



发自我的 iPad


------------------ 原始邮件 ------------------
发件人: pjd <notifications@github.com&gt;
发送时间: 2019年12月20日 10:47
收件人: pprp/captcha_identify.pytorch <captcha_identify.pytorch@noreply.github.com&gt;
抄送: YaooXu <614282119@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[pprp/captcha_identify.pytorch] 验证集正确率的问题 (#2)




https://github.com/pprp/captcha.Pytorch
 这是我最新开源的模型更加丰富的库，比当前的库更容易调参，欢迎试试

**Comment by pprp** [comment]
@YaooXu 感谢指点
