### ISSUE TITLE
关于模型正确率的问题

### ISSUE THREAD

**Issue by schrodingercatss** [pprp/captcha_identify.pytorch#5]
这里我采用了1w的训练集，跑了100个epoch，验证码是五位数字+小写+大写字母混合型，正确率只有20%不到，需要改变神经网络模型吗？

**Comment by pprp** [comment]
模型本身对准确率影响比较大，不过建议首先先调一下learning rate参数，如果不行的话推荐使用resnet18这个模型，这个模型对验证码识别问题比较普适。
